version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elastic_search
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
    ports:
      - "9200:9200" #HTTP access
      - "9300:9300" # for internal coms
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - es_network
    restart: always

  redis:
    image: redis:latest
    container_name: redis_local
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-net
    restart: always

volumes:
  redis-data:
  elasticsearch-data:

networks:
  es_network:
    driver: bridge
  redis-net:
    driver: bridge