version: '3.8'

services:
# #zookeeper
#   zookeeper:
#     image: wurstmeister/zookeeper:latest
#     container_name: zookeeper
#     ports:
#       - "2181:2181"
#     networks:
#       - kafka-net
#     environment:
#       ZOOKEEPER_SERVER_ID: 1
#       ZOOKEEPER_LISTENER_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#       ZOOKEEPER_INIT_LIMIT: 10
#       ZOOKEEPER_SYNC_LIMIT: 5
    


# #kafka
#   kafka:
#     image: wurstmeister/kafka:latest
#     container_name: kafka
#     ports:
#       - "9096:9096" #external port mapping
#       - "9094:9094" #internal port mapping
#     environment:
#      # Define listeners with new ports
#       KAFKA_LISTENERS: INSIDE://0.0.0.0:9094,OUTSIDE://0.0.0.0:9096
#       KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9094,OUTSIDE://localhost:9096
      
#       # Map listeners to security protocols
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT

#       # Define the listener for internal broker communication
#       KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

#       # Zookeeper connection string
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

#       # Replication factor for single-broker setup
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

#     depends_on:
#       - zookeeper
#     networks:
#       - kafka-net


#elastic search
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elastic_search
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
    ports:
      - "9200:9200" #HTTP access
      - "9300:9300" # for internal coms
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - es_network
    restart: always

  redis:
    image: redis:latest
    container_name: redis_local
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-net
    restart: always

volumes:
  redis-data:
  elasticsearch-data:

networks:
  es_network:
    driver: bridge
  redis-net:
    driver: bridge
 